// Generates fresh wallets for every role and writes .env (never overwrites an
// existing .env). Prints addresses + faucet links.

import fs from "node:fs";
import path from "node:path";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

const ENV_PATH = path.join(process.cwd(), ".env");
const ROLES = ["PROVIDER1", "PROVIDER2", "PROVIDER3", "AGENT", "VERIFIER", "EXCHANGE"];

if (fs.existsSync(ENV_PATH)) {
  console.log(".env already exists — not touching it. Delete it to regenerate.");
  const content = fs.readFileSync(ENV_PATH, "utf8");
  for (const role of ROLES) {
    const m = content.match(new RegExp(`${role}_PK=(0x[0-9a-fA-F]{64})`));
    if (m) console.log(`${role}: ${privateKeyToAccount(m[1] as `0x${string}`).address}`);
  }
  process.exit(0);
}

let env = `# Generated by pnpm gen-wallets on ${new Date().toISOString()}\nMOCK_MODE=true\nGROQ_API_KEY=\nCHEAT_MODE=true\n`;
console.log("Generated wallets (fund AGENT + EXCHANGE with Base Sepolia ETH + USDC for real mode):\n");
for (const role of ROLES) {
  const pk = generatePrivateKey();
  const addr = privateKeyToAccount(pk).address;
  env += `${role}_PK=${pk}\n`;
  console.log(`  ${role.padEnd(10)} ${addr}`);
}
fs.writeFileSync(ENV_PATH, env);
console.log(`\nWrote ${ENV_PATH}`);
console.log("Faucets: ETH → https://portal.cdp.coinbase.com/products/faucet | USDC → https://faucet.circle.com (Base Sepolia)");
